// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Police_Case_Table_Insertion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Police_Case_Table_Insertion));
        
        string IMigrationMetadata.Id
        {
            get { return "202212252330246_Police_Case_Table_Insertion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
